import { Alert, AIInsight, HourlySalesPoint, IncidentRecord, MetricCardData } from './types'

export const mockAlerts: Alert[] = [
  {
    id: '1a2b3c4d-0001',
    severity: 'critical',
    module: 'Checkout',
    title: 'Taxa de conversão abaixo do limiar crítico',
    description: 'Conversão caiu 38% nas últimas 2 horas. Atual: 1.2% vs baseline 1.9%. Possível problema no fluxo de pagamento.',
    source: 'nuvemshop',
    status: 'investigating',
    created_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    notified_whatsapp: true,
  },
  {
    id: '1a2b3c4d-0002',
    severity: 'high',
    module: 'Pagamentos',
    title: 'Aumento nas recusas de cartão',
    description: 'Taxa de aprovação de cartão em 87.3% — queda de 6.9pp vs média 94.2%. Verifique gateway de pagamento.',
    source: 'nuvemshop',
    status: 'open',
    created_at: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    notified_whatsapp: true,
  },
  {
    id: '1a2b3c4d-0003',
    severity: 'medium',
    module: 'Instagram',
    title: 'Cluster de reclamações detectado',
    description: '7 menções negativas sobre "prazo de entrega" identificadas nos últimos 30 minutos. IA classificou como padrão de insatisfação.',
    source: 'instagram',
    status: 'open',
    created_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    notified_whatsapp: false,
  },
  {
    id: '1a2b3c4d-0004',
    severity: 'low',
    module: 'Cupons',
    title: 'Cupom VERAO30 com alto uso',
    description: 'Cupom VERAO30 utilizado em 34 pedidos hoje (18% dos pedidos). Dentro do normal para campanha ativa.',
    source: 'nuvemshop',
    status: 'resolved',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    notified_whatsapp: false,
  },
  {
    id: '1a2b3c4d-0005',
    severity: 'high',
    module: 'Site',
    title: 'Tempo de resposta elevado',
    description: 'Latência média do site em 2.8s — acima do SLA de 1.5s. CDN com possível sobrecarga. Uptime 99.1%.',
    source: 'monitoramento',
    status: 'investigating',
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    notified_whatsapp: true,
  },
]

export const mockHourlySales: HourlySalesPoint[] = [
  { hour: '00h', today: 420, yesterday: 380 },
  { hour: '01h', today: 210, yesterday: 190 },
  { hour: '02h', today: 95, yesterday: 110 },
  { hour: '03h', today: 60, yesterday: 75 },
  { hour: '04h', today: 45, yesterday: 55 },
  { hour: '05h', today: 85, yesterday: 90 },
  { hour: '06h', today: 320, yesterday: 290 },
  { hour: '07h', today: 780, yesterday: 650 },
  { hour: '08h', today: 1450, yesterday: 1280 },
  { hour: '09h', today: 2340, yesterday: 2100 },
  { hour: '10h', today: 3120, yesterday: 2850 },
  { hour: '11h', today: 3890, yesterday: 3560 },
  { hour: '12h', today: 4200, yesterday: 3980 },
  { hour: '13h', today: 3750, yesterday: 3820 },
  { hour: '14h', today: 4580, yesterday: 4100 },
  { hour: '15h', today: 5230, yesterday: 4750 },
  { hour: '16h', today: 4980, yesterday: 5100 },
  { hour: '17h', today: 5640, yesterday: 5200 },
  { hour: '18h', today: 6120, yesterday: 5780 },
  { hour: '19h', today: 5890, yesterday: 5650 },
  { hour: '20h', today: 4320, yesterday: 4580 },
  { hour: '21h', today: 3210, yesterday: 3480 },
  { hour: '22h', today: 1890, yesterday: 2100 },
  { hour: '23h', today: 890, yesterday: 1050 },
]

export const mockMetricCards: MetricCardData[] = [
  {
    id: 'revenue',
    label: 'Faturamento Hoje',
    value: 'R$ 47.832',
    rawValue: 47832,
    change: 12.4,
    changeLabel: 'vs ontem',
    positive: true,
    icon: 'DollarSign',
  },
  {
    id: 'orders',
    label: 'Pedidos em Tempo Real',
    value: '127',
    rawValue: 127,
    change: 8.5,
    changeLabel: 'vs ontem',
    positive: true,
    icon: 'ShoppingBag',
  },
  {
    id: 'ticket',
    label: 'Ticket Médio',
    value: 'R$ 376',
    rawValue: 376,
    change: 3.2,
    changeLabel: 'vs ontem',
    positive: true,
    icon: 'TrendingUp',
  },
  {
    id: 'card_approval',
    label: 'Aprovação Cartão',
    value: '94.2%',
    rawValue: 94.2,
    change: -6.9,
    changeLabel: 'vs média 7d',
    positive: false,
    icon: 'CreditCard',
  },
  {
    id: 'pix_orders',
    label: 'Pedidos PIX',
    value: '63',
    rawValue: 63,
    change: 22.1,
    changeLabel: 'vs ontem',
    positive: true,
    icon: 'Zap',
  },
  {
    id: 'coupons',
    label: 'Uso de Cupons',
    value: '34',
    rawValue: 34,
    change: 5.8,
    changeLabel: 'vs ontem',
    positive: true,
    icon: 'Tag',
  },
  {
    id: 'conversion',
    label: 'Conversão',
    value: '1.2%',
    rawValue: 1.2,
    change: -38.1,
    changeLabel: 'vs baseline',
    positive: false,
    icon: 'BarChart2',
  },
  {
    id: 'checkout',
    label: 'Status Checkout',
    value: 'Operacional',
    rawValue: 1,
    change: 0,
    changeLabel: 'último check 1min',
    positive: true,
    icon: 'CheckCircle',
    status: 'degraded',
  },
  {
    id: 'uptime',
    label: 'Estabilidade Site',
    value: '99.1%',
    rawValue: 99.1,
    change: -0.4,
    changeLabel: 'vs semana',
    positive: false,
    icon: 'Wifi',
    status: 'online',
  },
]

export const mockAIInsights: AIInsight[] = [
  {
    id: 'ai-001',
    insight_type: 'anomaly',
    title: 'Padrão de Abandono Detectado',
    summary: 'Identificado aumento de 42% em abandonos de carrinho entre 14h-16h. Correlação com lentidão no checkout. Recomendação: verificar integração com gateway de pagamento e otimizar loading do checkout.',
    confidence: 0.89,
    severity: 'high',
    related_alert_ids: ['1a2b3c4d-0001', '1a2b3c4d-0005'],
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'ai-002',
    insight_type: 'opportunity',
    title: 'Oportunidade de Remarketing',
    summary: 'Segmento de clientes com ticket > R$500 apresentou queda de 18% hoje. Possível impacto do concorrente com promoção ativa. Sugestão: ativar campanha de retenção para clientes VIP com desconto de 10%.',
    confidence: 0.74,
    severity: 'medium',
    created_at: new Date(Date.now() - 1.2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ai-003',
    insight_type: 'prediction',
    title: 'Projeção de Faturamento 24h',
    summary: 'Com base no ritmo atual e histórico de sexta-feira, projeção de faturamento diário é R$62.400 ± R$4.200. Meta era R$58.000. Tendência positiva, mas dependente de recuperação da conversão.',
    confidence: 0.81,
    severity: 'low',
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
]

export const mockIncidents: IncidentRecord[] = [
  {
    id: 'inc-001',
    severity: 'critical',
    module: 'Checkout',
    description: 'Queda completa do gateway PagSeguro — 100% das transações falhando por 12 minutos',
    start_time: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString(),
    status: 'resolved',
    duration: '12 min',
  },
  {
    id: 'inc-002',
    severity: 'high',
    module: 'Conversão',
    description: 'Taxa de conversão caiu 38% — investigação em andamento, possível problema no fluxo de pagamento',
    start_time: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    status: 'investigating',
  },
  {
    id: 'inc-003',
    severity: 'high',
    module: 'Site',
    description: 'Latência média 2.8s — CDN com sobrecarga, equipe técnica notificada',
    start_time: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    status: 'ongoing',
  },
  {
    id: 'inc-004',
    severity: 'medium',
    module: 'Instagram',
    description: 'Pico de menções negativas sobre entrega — 7 reclamações em 30 min, atendimento acionado',
    start_time: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    status: 'ongoing',
  },
  {
    id: 'inc-005',
    severity: 'critical',
    module: 'Pagamentos',
    description: 'Falha no processamento de PIX — 23 transações pendentes por 8 minutos, Banco Central instabilidade',
    start_time: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    end_time: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
    status: 'resolved',
    duration: '8 min',
  },
]
